source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CGRefresh_Example' do
  pod 'CGRefresh', :path => '../'
end

target 'CGRefresh_Tests' do
  pod 'CGRefresh', :path => '../'
end
